package com.example.whoowesme.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Environment
import androidx.core.content.FileProvider
import com.example.whoowesme.model.MoneyTransaction
import com.example.whoowesme.model.Person
import com.example.whoowesme.model.enums.TransactionType
import com.itextpdf.kernel.colors.DeviceRgb
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Cell
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.UnitValue
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfGenerator {
    fun generateAndShareStatement(
        context: Context,
        person: Person,
        transactions: List<MoneyTransaction>,
        totalBalance: Double
    ) {
        val fileName = "Statement_${person.name.replace(" ", "_")}.pdf"
        val file = File(context.cacheDir, fileName) // Use cache dir for temporary sharing
        
        try {
            val writer = PdfWriter(FileOutputStream(file))
            val pdf = PdfDocument(writer)
            val document = Document(pdf)

            // Header
            document.add(Paragraph("Who Owes Me - Transaction Statement")
                .setBold()
                .setFontSize(18f)
                .setTextAlignment(TextAlignment.CENTER)
                .setFontColor(DeviceRgb(63, 81, 181)))
            
            document.add(Paragraph("\n"))
            
            // Person Info
            document.add(Paragraph("Name: ${person.name}").setBold())
            if (person.phoneNumber.isNotEmpty()) {
                document.add(Paragraph("Phone: ${person.phoneNumber}"))
            }
            document.add(Paragraph("Date Generated: ${SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault()).format(Date())}"))
            
            // Balance Section
            val balanceText = if (totalBalance >= 0) "Amount Receivable: ₹ " else "Amount Payable: ₹ "
            val balanceColor = if (totalBalance >= 0) DeviceRgb(0, 150, 136) else DeviceRgb(244, 67, 54)
            
            document.add(Paragraph("$balanceText${String.format(Locale.getDefault(), "%,.2f", Math.abs(totalBalance))}")
                .setBold()
                .setFontSize(14f)
                .setFontColor(balanceColor))
            
            document.add(Paragraph("\n"))

            // Transactions Table
            val table = Table(UnitValue.createPointArray(floatArrayOf(80f, 60f, 80f, 150f)))
            table.width = UnitValue.createPercentValue(100f)
            
            // Table Header
            val headerBg = DeviceRgb(240, 240, 240)
            table.addHeaderCell(Cell().add(Paragraph("Date").setBold()).setBackgroundColor(headerBg))
            table.addHeaderCell(Cell().add(Paragraph("Type").setBold()).setBackgroundColor(headerBg))
            table.addHeaderCell(Cell().add(Paragraph("Amount").setBold()).setBackgroundColor(headerBg))
            table.addHeaderCell(Cell().add(Paragraph("Note").setBold()).setBackgroundColor(headerBg))

            val dateFormat = SimpleDateFormat("dd/MM/yy", Locale.getDefault())
            transactions.sortedBy { it.date }.forEach { tx ->
                table.addCell(dateFormat.format(Date(tx.date)))
                table.addCell(if (tx.type == TransactionType.GIVEN) "Gave" else "Returned")
                table.addCell(String.format(Locale.getDefault(), "%.2f", tx.amount))
                table.addCell(tx.note)
            }

            document.add(table)
            
            // Footer
            document.add(Paragraph("\n\nGenerated by Who Owes Me App")
                .setFontSize(10f)
                .setItalic()
                .setTextAlignment(TextAlignment.CENTER)
                .setFontColor(DeviceRgb(150, 150, 150)))
            
            document.close()
            
            shareFile(context, file)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun shareFile(context: Context, file: File) {
        val uri: Uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        
        context.startActivity(Intent.createChooser(intent, "Share Statement via"))
    }
}
